### ISSUE TITLE
Procedure to generate files for JRL website

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/bibmanagement#1]
@aescande, thank you for these scripts. Could you add the following information to README, so that we can continue to update JRL web pages?

How do you install the scripts in this repo, and how exactly do you call the functions in websitePubli.py to reproduce the auto-generated files in https://github.com/jrl-umi3218/jrl-umi3218.github.com (maybe you call websitePubli.generateYamlJRL, but what arguments do you pass)?

**Comment by GuicarMIS** [comment]
@aescande, maybe you don't have time to do it but is there someone else who knows this procedure?

**Comment by fkanehiro** [comment]
I tried the following procedure locally and it seemed to work.

1. create `gen.py` in `script` directory
```
import websitePubli

websitePubli.generateYamlJRL(<jrl-publi>, <jrl-umi3218.github.com>, True)
```
2. in `src` directory, execute `python3 ../script/gen.py`
3. `mv <jrl-publi>/tmp/*.bib <jrl-umi3218.github.com>/en/assets/bib`
4. `mv <jrl-publi>/tmp/publications.yml <jrl-umi3218.github.com>/_data`

**Comment by mmurooka** [comment]
@fkanehiro Did you do some installation procedure beforehand?
In the step 2, I got the errors of not finding Python packages. I installed them by pip one by one, but I got the following error.

```bash
~/src/bibmanagement/src$ python3 ../scripts/gen.py 
Traceback (most recent call last):
  File "../scripts/gen.py", line 1, in <module>
    import websitePubli
  File "/home/mmurooka/src/bibmanagement/scripts/websitePubli.py", line 5, in <module>
    from bibmanagement import Biblio
  File "/home/mmurooka/src/bibmanagement/src/bibmanagement/Biblio.py", line 12, in <module>
    from docx import Document
  File "/home/mmurooka/.local/lib/python3.6/site-packages/docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'
```

**Comment by mmurooka** [comment]
> @fkanehiro Did you do some installation procedure beforehand?

Sorry, just after doing the following in `bibmanagement` directory, I succeeded the all steps.
```
pip3 install -r ./requirements.txt
```

**Comment by mmurooka** [comment]
The procedure in https://github.com/jrl-umi3218/bibmanagement/issues/1#issuecomment-1237884191 is working, so I close this.
